# https://docs.coderabbit.ai/guides/configure-coderabbit
reviews:
  sequence_diagrams: false
  review_status: true
  fail_commit_status: true
  profile: assertive
  poem: false
  path_filters:
    - "!**/.specify/**"
  auto_review:
    enabled: true
    ignore_usernames:
      []
    request_changes_workflow: true
  tools:
    markdownlint:
      enabled: false
