# https://docs.coderabbit.ai/guides/configure-coderabbit
reviews:
  sequence_diagrams: false
  review_status: true
  profile: assertive
  auto_review:
    enabled: true
    ignore_usernames:
      []
    request_changes_workflow: true
  tools:
    markdownlint:
      enabled: false
